---
title: "Remote proctoring"
author: "Sharon Klinkenberg"
output:
  revealjs::revealjs_presentation:
    theme: white
    highlight: pygments
    center: true
---

* Docent aan de Universiteit van Amsterdam
* Onderzoek computer adaptief toetsen
* Voorzitter opleidingscommissie
* Voorzitter Special Interest Group Digitaal Toetsen
* Lid van de Werkgroep Toetsen op Afstand

# Versnellingplan

De [Werkgroep Toetsen op Afstand](http://www.versnellingsplan.nl/werkgroep-toetsen-op-afstand/) is onderdeel van het versnellingsplan onderwijsinnovatie met ICT.

# NRO Symposium hoger onderwijs

[Toetsen op afstand en monitoren van de studievoortgang](https://www.onderwijskennis.nl/nro-symposium-hoger-onderwijs-nieuwe-richtingen-na-de-pandemie/toetsen-op-afstand-en-monitoren-van-de-studievoortgang)

Essays, posters en kennisclips van:

* [Desirée Joosten-ten Brinke](https://www.linkedin.com/in/desirée-joosten-ten-brinke-15a9905/?originalSubdomain=nl)
* [Kim Schildkamp](https://www.linkedin.com/in/kim-schildkamp/)
* [Sharon Klinkenberg](https://www.linkedin.com/in/sharonklinkenberg/)

# Gedifferentieerd onderwijs

> In de strategische agenda van 2015-2025 (OCW, 2015) pleit men voor meer flexibele leerwegen om het onderwijs meer toe te spitsen op de individuele behoeften.

# Digitaal toetsen

* Versneld ingevoerd
* Plaats en tijd onafhankelijk extra

## Plaatsonafhankelijk {data-background=young-woman-with-laptop-computer-for-homework-tired-hispanic-girl-and-college-educatio-SBI-310097751.jpg #white}

<br><br><br><br><br><br>

## Tijdonafhankelijk {data-background=vector-abstract-line-art-texture-SBI-300528717.png}

<br><br><br><br><br><br><br><br>

## Toekomstperspectief

* Studenten met functie beperking
* Speciale groepen (topsporters)
* Toelatings toetsen
* Keuze voor stuenten

## Alleen formatief?

```{r, echo=FALSE, fig.align='center', fig.asp=1, fig.width=6}
set.seed(154)
x = rnorm(100)
y = x + rnorm(100, 0, 3)

q.x = quantile(x, .55)
q.y = quantile(y, .55)

plot(x,y, xlab="Formatief", ylab="Summatief", xaxt="n", yaxt="n", main = paste("Correlatie =", round(cor(x,y),2)))

polygon(c(q.x,4,4,q.x),c(q.y,q.y,-8,-8),col = rgb(1,0,0,.5))
polygon(c(q.x,-8,-8,q.x),c(q.y,q.y,10,10),col = rgb(1,0,0,.5))
```

# Conclusie

> * Tijd onafhankelijk nog te voorbarig
> * Plaats onafhankelijk is mogelijk
> * Formatief toetsen is geen vervanging

# Contact

<script src="https://use.fontawesome.com/23c1d38eea.js"></script>

<ul class="fa-ul" style="color:black; list-style:none;">
<li><i class="fa-li fa fa-twitter"></i> <a href="https://twitter.com/shklinkenberg" target="_blank" style="color:black; border-bottom:none;">@shklinkenberg</a></li>
<li><i class="fa-li fa fa-linkedin-square"></i> <a href="https://www.linkedin.com/in/sharonklinkenberg/" target="_blank" style="color:black; border-bottom:none;">Klinkenberg</a></li>
<li><i class="fa-li fa fa-envelope-o"></i> <a style="unicode-bidi:bidi-override; direction: rtl; color:black" href="javascript:window.location.href = 'mailto:' + ['s.klinkenberg','uva.nl'].join('@')">ln.AvU@grebneknilK.S</a></li>
<li><i class="fa-li fa fa-github"></i> <a href="https://github.com/ShKlinkenberg" target="_blank" style="color:black; border-bottom:none;">ShKlinkenberg</a></li>
</ul>




